= sycl_ext_oneapi_usm_malloc_properties

:source-highlighter: coderay
:coderay-linenums-mode: table

// This section needs to be after the document title.
:doctype: book
:toc2:
:toc: left
:encoding: utf-8
:lang: en

:blank: pass:[ +]

// Set the default source code type in this document to C++,
// for syntax highlighting purposes.  This is needed because
// docbook uses c++ and html5 uses cpp.
:language: {basebackend@docbook:c++:cpp}

// This is necessary for asciidoc, but not for asciidoctor
:cpp: C++
:dpcpp: DPC++

== Notice

Copyright (c) 2022 Intel Corporation.  All rights reserved.

NOTE: Khronos(R) is a registered trademark and SYCL(TM) and SPIR(TM) are
trademarks of The Khronos Group Inc.  OpenCL(TM) is a trademark of Apple Inc.
used by permission by Khronos.

== Contact

Jessica Davies, Intel (jessica 'dot' davies 'at' intel 'dot' com)

== Contributors

Jessica Davies, Intel +
Joe Garvey, Intel +
Michael Kinsner, Intel +
Aditi Kumaraswamy, Intel +
Steffen Larsen, Intel +
Gregory Lueck, Intel +
John Pennycook, Intel +
Roland Schulz, Intel +
Jason Sewall, Intel +
Abhishek Tiwari, Intel +
Sherry Yuan, Intel

== Dependencies

This extension is written against the SYCL 2020 specification, revision 5.
All references below to the "core SYCL specification" or to section numbers in the
SYCL specification refer to that revision.

This extension also depends on the following other SYCL extensions:

- link:../experimental/sycl_ext_oneapi_properties.asciidoc[sycl_ext_oneapi_properties]
- link:../proposed/sycl_ext_oneapi_annotated_ptr.asciidoc[sycl_ext_oneapi_annotated_ptr]

== Status

This is a proposed extension specification, intended to gather community
feedback.  Interfaces defined in this specification may not be implemented yet
or may be in a preliminary state.  The specification itself may also change in
incompatible ways before it is finalized.  *Shipping software products should
not rely on APIs defined in this specification.*

== Overview

This extension introduces USM memory allocation functions with support for compile-time-constant and runtime properties, as defined in the link:../experimental/sycl_ext_oneapi_properties.asciidoc[sycl_ext_oneapi_properties] extension.
The USM memory allocation functions introduced by this extension take a `properties` object as a parameter, and return an `annotated_ptr`.
This allows both runtime and compile-time-constant properties to be specified when allocating USM memory.
Furthermore, the annotated_ptr returned by the USM memory allocation functions allows compile-time-constant information to propagate to the device compiler and thereby enable additional optimization of kernel code.
This extension also introduces a new compile-time constant property `usm_alloc`, with three possible values: `usm_alloc_kind::device`, `usm_alloc_kind::host`, and `usm_alloc_kind::shared`.

[NOTE]
====
In this document, we use the shortened form `annotated_ptr` to refer to the
proposed `sycl::ext::oneapi::experimental::annotated_ptr` class.
We also use the shortened form `properties` to refer to the `sycl::ext::oneapi::experimental::properties` class.
====

The purpose of this document is to clearly describe and specify USM memory allocation functions with `properties` support,
and related concepts, types, and mechanisms, and to give examples and context for their usage.

== Examples

Runtime and compile-time constant properties can be passed to the USM memory allocation functions with `properties` support introduced by this extension.
Properties passed to the USM memory allocation functions with `properties` support may or may not appear on the returned `annotated_ptr` object:
compile-time constant properties will appear on the `annotated_ptr`, while runtime properties will not.

In the following examples, `bar` and `baz` are compile-time-constant properties, while `foo` is a
runtime property. Therefore if `bar` or `baz` is passed to a USM memory allocation function with `properties` support, it will appear on the returned `annotated_ptr`.
However, the `foo` property will not appear on the returned `annotated_ptr` because it is a runtime property.

[source,c++]
----
using namespace sycl::ext::oneapi::experimental;

properties P1{bar, baz, foo{1}};
properties P2{bar, foo{2}};
properties P3{bar, baz}

// APtr1 is of type annotated_ptr<int*, decltype(properties{bar, baz})>
auto APtr1 = malloc_device<int>(N, q, P1);

// APtr2 is of type annotated_ptr<int*, decltype(properties{bar})>
auto APtr2 = malloc_device<int>(N, q, P2);

// APtr3 is of type annotated_ptr<int*, decltype(properties{bar, baz})>
auto APtr3 = malloc_device<int>(N, q, P3);

// Runtime properties are not present on the returned annotated_ptr
static_assert(std::is_same_v<decltype(APtr1), decltype(APtr3)>);

// APtr1 and APtr2 do not have the same properties
static_assert(!std::is_same_v<decltype(APtr1), decltype(APtr2)>);
----

The following example uses the compile-time-constant property `alignment`, defined in the link:../proposed/sycl_ext_oneapi_annotated_ptr.asciidoc[sycl_ext_oneapi_annotated_ptr] extension.
When `alignment` is passed to a USM memory allocation function with `properties` support, it will appear on the returned `annotated_ptr` since it is a compile-time constant property.
It also informs the runtime to allocate the memory with this alignment.

[source,c++]
----
using namespace sycl::ext::oneapi::experimental;

properties P1{alignment<512>};
// APtr1 is of type annotated_ptr<int, decltype(properties{alignment<512>})>
// The raw pointer of APtr1 is aligned to 512 bytes
auto APtr1 = malloc_device<int>(N, q, P1);

properties P2{alignment<1>};
// Allocate N integers.
// Alignment must be at least sizeof(int) bytes.
auto APtr2 = malloc_device<int>(N, q, P2); // Error

properties P3{alignment<64>};
// Allocate 512 bytes.
// Alignment must be at least 512 bytes.
auto APtr3 = malloc_device(512, q, P3); // Exception
----

== Specification

=== Feature test macro

This extension provides a feature-test macro as described in the core SYCL
specification, Section 6.3.3 "Feature test macros". Therefore, an
implementation supporting this extension must predefine the macro
`SYCL_EXT_ONEAPI_USM_MALLOC_PROPERTIES` to one of the values defined in the table below.
Applications can test for the existence of this macro to determine if the
implementation supports this feature, or applications can test the macro's
value to determine which of the extension's features
the implementation supports.

[%header,cols="1,5"]
|===
|Value |Description
|1     |Initial extension version
|===

=== Orientation

The core SYCL specification lists eight functions in each of the following four tables:

- Table 103 "USM Device Memory Allocation Functions", of Section 4.8.3.2 "Device allocation functions" +
- Table 104 "USM Host Memory Allocation Functions", of Section 4.8.3.3 "Host allocation functions" +
- Table 105 "USM Shared Memory Allocation Functions", of Section 4.8.3.4 "Shared allocation functions" +
- Table 106 "USM Parameterized Allocation Functions", of Section 4.8.3.5 "Parameterized allocation functions"

This extension introduces a new function for each function listed in the above tables of the core SYCL specification, except for the USM allocation functions that take an alignment parameter.
For the sake of clarity, we first describe how the new functions differ from the corresponding functions in the core SYCL specification. All APIs introduced by this extension are listed explicitly in Section <<section.usm.allocs>>.

[NOTE]
====
This extension does not introduce any functions that take an alignment parameter, because alignment can be specified using the compile-time constant `alignment` property instead.
====

[NOTE]
====
The USM memory allocation functions defined in the core SYCL specification can be used in the same program as the USM memory allocation functions with `properties` support defined in this extension.
The new functions are distinguished by their namespace, and their non-optional `properties` parameter.
====

The following table lists phrases which appear in the the above tables of the core SYCL specification, and how they are replaced to generate the corresponding tables in this extension.
The parameters of each function introduced by this extension are the same as the parameters of the corresponding function in the core SYCL specification, except for the parameter of type `sycl::property_list`.

[options="header"]
|====
| Core SYCL | USM memory allocation functions with `properties` support
a|
sycl::malloc +
sycl::malloc_device +
sycl::malloc_host +
sycl::malloc_shared
|
sycl::ext::oneapi::experimental::malloc +
sycl::ext::oneapi::experimental::malloc_device +
sycl::ext::oneapi::experimental::malloc_host +
sycl::ext::oneapi::experimental::malloc_shared
a|
sycl::aligned_alloc
sycl::aligned_alloc_device +
sycl::aligned_alloc_host +
sycl::aligned_alloc_shared
|
This extension does not introduce any corresponding functions.
a|
The USM memory allocation function is a function template `template <typename T>` returning `T *`.
|
The corresponding USM memory allocation function with `properties` support is a function template
`template<typename T, typename propertyListA, typename propertyListB>` returning `annotated_ptr<T, propertyListB>`.
a|
The USM memory allocation funtion is not a function template, and returns `void *`.
|
The corresponding USM memory allocation function with `properties` support is a function template
`template<typename propertyListA, typename propertyListB>` returning `annotated_ptr<void, propertyListB>`.
a|
The last parameter of the USM memory allocation function is an optional `const property_list &propList = {}`.
|
The last parameter of the corresponding USM memory allocation function with `properties` support is a non-optional `const propertyListA &propList`.
a|
Zero or more properties can be provided to the allocation function via an instance of `property_list`.
|
Zero or more runtime and compile-time constant properties can be provided to the allocation function via an instance of `properties`.
The compile-time constant properties in `propList` will appear as properties of the returned `annotated_ptr`.
Runtime properties in `propList` will not appear as properties of the returned `annotated_ptr`.
a|
On failure, returns [code]#nullptr#.
|
On failure, the raw pointer of the returned `annotated_ptr` will be [code]#nullptr#.
|====

The descriptions of functions introduced by this extension contain the following sentences:

[options="header"]
|====
| Function | Sentences appended to the Description
a|
Any of the functions specified in this extension.
|
Available only if `propertyListA` and `propertyListB` are specializations of the `properties` class.
|====

[[section.usm.allocs]]
=== USM Memory Allocation Functions with properties Support

The following five tables list all functions introduced by this extension.


[[section.usm.device.allocs]]
==== Device allocation functions with properties support

[[table.usm.device.allocs]]
.USM Device Memory Allocation Functions with properties Support
[width="100%",options="header",separator="@",cols="65%,35%"]
|====
@ Function @ Description
a@
[source]
----
template<typename propertyListA, typename propertyListB>
sycl::ext::oneapi::experimental::annotated_ptr<void, propertyListB>
sycl::ext::oneapi::experimental::malloc_device(size_t numBytes,
                                               const device& syclDevice,
                                               const context& syclContext,
                                               const propertyListA &propList)
----
a@ Returns an `annotated_ptr` containing a raw pointer to the newly allocated memory on [code]#syclDevice# on
success.  The allocation size is specified in bytes.  This memory is not
accessible on the host.  Memory allocated by [code]#sycl::ext::oneapi::experimental::malloc_device#
must be deallocated with [code]#sycl::free# to avoid memory leaks.
On failure, the raw pointer of the returned `annotated_ptr` will be [code]#nullptr#.

Zero or more runtime and compile-time constant properties can be provided to the
allocation function via an instance of `properties`.
The compile-time constant properties in `propList` will appear as properties of the returned `annotated_ptr`.
Runtime properties in `propList` will not appear as properties of the returned `annotated_ptr`.

Throws a
synchronous [code]#exception# with the [code]#errc::feature_not_supported#
error code if the [code]#syclDevice# does not have
[code]#aspect::usm_device_allocations#.  The [code]#syclDevice# must either be
contained by [code]#syclContext# or it must be a descendent device of some
device that is contained by that context, otherwise this function throws a
synchronous [code]#exception# with the [code]#errc::invalid# error code.
Available only if `propertyListA` and `propertyListB` are specializations of the `properties` class.

a@
[source]
----
template <typename T, typename propertyListA, typename propertyListB>
sycl::ext::oneapi::experimental::annotated_ptr<T, propertyListB>
sycl::ext::oneapi::experimental::malloc_device(size_t count,
                                               const device& syclDevice,
                                               const context& syclContext,
                                               const propertyListA &propList)
----
a@  Returns an `annotated_ptr` containing a raw pointer to the newly allocated memory on [code]#syclDevice# on
success.  The allocation size is specified in number of elements of type
[code]#T#.  This memory is not accessible on the host.  Memory allocated
by [code]#sycl::ext::oneapi::experimental::malloc_device# must be deallocated with
[code]#sycl::free# to avoid memory leaks.
On failure, the raw pointer of the returned `annotated_ptr` will be [code]#nullptr#.

Zero or more runtime and compile-time constant properties can be provided to the allocation function
via an instance of `properties`.
The compile-time constant properties in `propList` will appear as properties of the returned `annotated_ptr`.
Runtime properties in `propList` will not appear as properties of the returned `annotated_ptr`.

Throws a synchronous [code]#exception# with the
[code]#errc::feature_not_supported# error code if the [code]#syclDevice#
does not have [code]#aspect::usm_device_allocations#.  The [code]#syclDevice#
must either be contained by [code]#syclContext# or it must be a
descendent device of some device that is contained by that context,
otherwise this function throws a synchronous [code]#exception# with the
[code]#errc::invalid# error code.
Available only if `propertyListA` and `propertyListB` are specializations of the `properties` class.

a@
[source]
----
template<typename propertyListA, typename propertyListB>
sycl::ext::oneapi::experimental::annotated_ptr<void, propertyListB>
sycl::ext::oneapi::experimental::malloc_device(size_t numBytes,
                                               const queue& syclQueue,
                                               const propertyListA &propList)
----
a@ Simplified form where [code]#syclQueue# provides the [code]#device#
and [code]#context#.

Zero or more runtime and compile-time constant properties can be provided to the allocation function
via an instance of `properties`.
The compile-time constant properties in `propList` will appear as properties of the returned `annotated_ptr`.
Runtime properties in `propList` will not appear as properties of the returned `annotated_ptr`.

Throws a synchronous [code]#exception# with the
[code]#errc::feature_not_supported# error code if the device
does not have [code]#aspect::usm_device_allocations#.

Available only if `propertyListA` and `propertyListB` are specializations of the `properties` class.

a@
[source]
----
template <typename T, typename propertyListA, typename propertyListB>
sycl::ext::oneapi::experimental::annotated_ptr<T, propertyListB>
sycl::ext::oneapi::experimental::malloc_device(size_t count,
                                               const queue& syclQueue,
                                               const propertyListA &propList)
----
a@ Simplified form where [code]#syclQueue# provides the [code]#device#
and [code]#context#.

Zero or more runtime and compile-time constant properties can be provided to the allocation function
via an instance of `properties`.
The compile-time constant properties in `propList` will appear as properties of the returned `annotated_ptr`.
Runtime properties in `propList` will not appear as properties of the returned `annotated_ptr`.

Throws a synchronous [code]#exception# with the
[code]#errc::feature_not_supported# error code if the device
does not have [code]#aspect::usm_device_allocations#.

Available only if `propertyListA` and `propertyListB` are specializations of the `properties` class.

|====

==== Host allocation functions with properties support

[[table.usm.host.allocs]]
.USM Host Memory Allocation Functions with properties Support
[width="100%",options="header",separator="@",cols="65%,35%"]
|====
@ Function @ Description
a@
[source]
----
template <typename propertyListA, typename propertyListB>
sycl::ext::oneapi::experimental::annotated_ptr<void, propertyListB>
sycl::ext::oneapi::experimental::malloc_host(size_t numBytes,
                                             const context& syclContext,
                                             const propertyListA &propList)
----
a@ Returns an `annotated_ptr` containing a raw pointer to the newly allocated host memory on
success. This allocation is specified in bytes. The allocation is
accessible on the host and devices contained in the specified [code]#context#.
Memory allocated by [code]#sycl::ext::oneapi::experimental::malloc_host# must be
deallocated with [code]#sycl::free# to avoid memory leaks.
On failure, the raw pointer of the returned `annotated_ptr` will be [code]#nullptr#.

Zero or more runtime and compile-time constant properties can be provided to the allocation function
via an instance of `properties`.
The compile-time constant properties in `propList` will appear as properties of the returned `annotated_ptr`.
Runtime properties in `propList` will not appear as properties of the returned `annotated_ptr`.

Only devices that have [code]#aspect::usm_host_allocations# may access the
memory allocated by this function.  Attempting to access the memory from
a device that does not have the aspect results in undefined behavior.

Available only if `propertyListA` and `propertyListB` are specializations of the `properties` class.

a@
[source]
----
template <typename T, typename propertyListA, typename propertyListB>
sycl::ext::oneapi::experimental::annotated_ptr<T, propertyListB>
sycl::ext::oneapi::experimental::malloc_host(size_t count,
                                             const context& syclContext,
                                             const propertyListA &propList)
----
a@ Returns an `annotated_ptr` containing a raw pointer to the newly allocated host memory on
success. This allocation is specified in number of elements of type [code]#T#.
The allocation is accessible on the host and devices contained in the
specified [code]#context#.
Memory allocated by [code]#sycl::ext::oneapi::experimental::malloc_host# must be
deallocated with [code]#sycl::free# to avoid memory leaks.
On failure, the raw pointer of the returned `annotated_ptr` will be [code]#nullptr#.

Zero or more runtime and compile-time constant properties can be provided to the allocation function
via an instance of `properties`.
The compile-time constant properties in `propList` will appear as properties of the returned `annotated_ptr`.
Runtime properties in `propList` will not appear as properties of the returned `annotated_ptr`.

Only devices that have [code]#aspect::usm_host_allocations# may access the
memory allocated by this function.  Attempting to access the memory from
a device that does not have the aspect results in undefined behavior.

Available only if `propertyListA` and `propertyListB` are specializations of the `properties` class.

a@
[source]
----
template <typename propertyListA, typename propertyListB>
sycl::ext::oneapi::experimental::annotated_ptr<void, propertyListB>
sycl::ext::oneapi::experimental::malloc_host(size_t numBytes,
                                             const queue& syclQueue,
                                             const propertyListA &propList)
----
a@ Simplified form where [code]#syclQueue# provides the [code]#context#.

Zero or more runtime and compile-time constant properties can be provided to the allocation function
via an instance of `properties`.
The compile-time constant properties in `propList` will appear as properties of the returned `annotated_ptr`.
Runtime properties in `propList` will not appear as properties of the returned `annotated_ptr`.

Only devices that have [code]#aspect::usm_host_allocations# may access the
memory allocated by this function.  Attempting to access the memory from
a device that does not have the aspect results in undefined behavior.

Available only if `propertyListA` and `propertyListB` are specializations of the `properties` class.

a@
[source]
----
template <typename T, typename propertyListA, typename propertyListB>
sycl::ext::oneapi::experimental::annotated_ptr<T, propertyListB>
sycl::ext::oneapi::experimental::malloc_host(size_t count,
                                             const queue& syclQueue,
                                             const propertyListA &propList)
----
a@ Simplified form where [code]#syclQueue# provides the [code]#context#.

Zero or more runtime and compile-time constant properties can be provided to the allocation function
via an instance of `properties`.
The compile-time constant properties in `propList` will appear as properties of the returned `annotated_ptr`.
Runtime properties in `propList` will not appear as properties of the returned `annotated_ptr`.

Only devices that have [code]#aspect::usm_host_allocations# may access the
memory allocated by this function.  Attempting to access the memory from
a device that does not have the aspect results in undefined behavior.

Available only if `propertyListA` and `propertyListB` are specializations of the `properties` class.

|====

==== Shared allocation functions with properties support

[[table.usm.shared.allocs]]
.USM Shared Memory Allocation Functions with properties Support
[width="100%",options="header",separator="@",cols="65%,35%"]
|====
@ Function @ Description
a@
[source]
----
template <typename propertyListA, typename propertyListB>
sycl::ext::oneapi::experimental::annotated_ptr<void, propertyListB>
sycl::ext::oneapi::experimental::malloc_shared(size_t numBytes,
                                               const device& syclDevice,
                                               const context& syclContext,
                                               const propertyListA &propList)
----
a@ Returns a shared allocation that is accessible on the host and
on [code]#syclDevice#.
This allocation is specified in bytes.  This memory
must be deallocated with [code]#sycl::free# to avoid memory leaks.
On failure, the raw pointer of the returned `annotated_ptr` will be [code]#nullptr#.

Zero or more runtime and compile-time constant properties can be provided to the allocation function
via an instance of `properties`.
The compile-time constant properties in `propList` will appear as properties of the returned `annotated_ptr`.
Runtime properties in `propList` will not appear as properties of the returned `annotated_ptr`.

Throws a synchronous [code]#exception# with the
[code]#errc::feature_not_supported# error code if the [code]#syclDevice#
does not have [code]#aspect::usm_shared_allocations#.  The [code]#syclDevice#
must either be contained by [code]#syclContext# or it must be a
descendent device of some device that is contained by that context,
otherwise this function throws a synchronous [code]#exception# with the
[code]#errc::invalid# error code.

Available only if `propertyListA` and `propertyListB` are specializations of the `properties` class.

a@
[source]
----
template <typename T, typename propertyListA, typename propertyListB>
sycl::ext::oneapi::experimental::annotated_ptr<T, propertyListB>
sycl::ext::oneapi::experimental::malloc_shared(size_t count,
                                               const device& syclDevice,
                                               const context& syclContext,
                                               const propertyListA &propList)
----
a@ Returns a shared allocation that is accessible on the host and
on [code]#syclDevice#.
This allocation is specified in number of elements of
type [code]#T#. This memory must be deallocated with [code]#sycl::free# to avoid
memory leaks.
On failure, the raw pointer of the returned `annotated_ptr` will be [code]#nullptr#.

Zero or more runtime and compile-time constant properties can be provided to the allocation function
via an instance of `properties`.
The compile-time constant properties in `propList` will appear as properties of the returned `annotated_ptr`.
Runtime properties in `propList` will not appear as properties of the returned `annotated_ptr`.

Throws a synchronous [code]#exception# with the
[code]#errc::feature_not_supported# error code if the [code]#syclDevice#
does not have [code]#aspect::usm_shared_allocations#.  The [code]#syclDevice#
must either be contained by [code]#syclContext# or it must be a
descendent device of some device that is contained by that context,
otherwise this function throws a synchronous [code]#exception# with the
[code]#errc::invalid# error code.

Available only if `propertyListA` and `propertyListB` are specializations of the `properties` class.

a@
[source]
----
template <typename propertyListA, typename propertyListB>
sycl::ext::oneapi::experimental::annotated_ptr<void, propertyListB>
sycl::ext::oneapi::experimental::malloc_shared(size_t numBytes,
                                               const queue& syclQueue,
                                               const propertyListA &propList)
----
a@ Simplified form where [code]#syclQueue# provides the [code]#device# and
[code]#context#.

Zero or more runtime and compile-time constant properties can be provided to the allocation function
via an instance of `properties`.
The compile-time constant properties in `propList` will appear as properties of the returned `annotated_ptr`.
Runtime properties in `propList` will not appear as properties of the returned `annotated_ptr`.

Throws a synchronous [code]#exception# with the
[code]#errc::feature_not_supported# error code if the device
does not have [code]#aspect::usm_shared_allocations#.

Available only if `propertyListA` and `propertyListB` are specializations of the `properties` class.

a@
[source]
----
template <typename T, typename propertyListA, typename propertyListB>
sycl::ext::oneapi::experimental::annotated_ptr<T, propertyListB>
sycl::ext::oneapi::experimental::malloc_shared(size_t count,
                                               const queue& syclQueue,
                                               const propertyListA &propList)
----
a@ Simplified form where [code]#syclQueue# provides the [code]#device# and
[code]#context#.

Zero or more runtime and compile-time constant properties can be provided to the allocation function
via an instance of `properties`.
The compile-time constant properties in `propList` will appear as properties of the returned `annotated_ptr`.
Runtime properties in `propList` will not appear as properties of the returned `annotated_ptr`.

Throws a synchronous [code]#exception# with the
[code]#errc::feature_not_supported# error code if the device
does not have [code]#aspect::usm_shared_allocations#.

Available only if `propertyListA` and `propertyListB` are specializations of the `properties` class.

|====

==== Parameterized allocation functions with properties support

[[table.usm.param.allocs]]
.USM Parameterized Allocation Functions with properties Support
[width="100%",options="header",separator="@",cols="65%,35%"]
|====
@ Function @ Description
a@
[source]
----
template <typename propertyListA, typename propertyListB>
sycl::ext::oneapi::experimental::annotated_ptr<void, propertyListB>
sycl::ext::oneapi::experimental::malloc(size_t numBytes,
                                        const device& syclDevice,
                                        const context& syclContext,
                                        usm::alloc kind,
                                        const propertyListA &propList)
----
a@ Returns a [code]#kind# allocation.
This allocation is specified in bytes. This memory
must be deallocated with [code]#sycl::free# to avoid memory leaks.
On failure, the raw pointer of the returned `annotated_ptr` will be [code]#nullptr#.
Zero or more runtime and compile-time constant properties can be provided to the allocation function
via an instance of `properties`.
The compile-time constant properties in `propList` will appear as properties of the returned `annotated_ptr`.
Runtime properties in `propList` will not appear as properties of the returned `annotated_ptr`.
The [code]#syclDevice# parameter is
ignored if [code]#kind# is [code]#usm::alloc::host#.  If [code]#kind# is not
[code]#usm::alloc::host#, [code]#syclDevice# must either be contained by
[code]#syclContext# or it must be a descendent device of some device that
is contained by that context, otherwise this function throws a synchronous
[code]#exception# with the [code]#errc::invalid# error code.

Available only if `propertyListA` and `propertyListB` are specializations of the `properties` class.

a@
[source]
----
template <typename T, typename propertyListA, typename propertyListB>
sycl::ext::oneapi::experimental::annotated_ptr<T, propertyListB>
sycl::ext::oneapi::experimental::malloc(size_t count,
                                        const device& syclDevice,
                                        const context& syclContext,
                                        usm::alloc kind,
                                        const propertyListA &propList)
----
a@ Returns a [code]#kind# allocation.
This allocation is specified in number of elements of type [code]#T#.
This memory must be deallocated with [code]#sycl::free# to avoid memory leaks.
On failure, the raw pointer of the returned `annotated_ptr` will be [code]#nullptr#.
Zero or more runtime and compile-time constant properties can be provided to the allocation function
via an instance of `properties`.
The compile-time constant properties in `propList` will appear as properties of the returned `annotated_ptr`.
Runtime properties in `propList` will not appear as properties of the returned `annotated_ptr`.
The [code]#syclDevice# parameter is
ignored if [code]#kind# is [code]#usm::alloc::host#.  If [code]#kind# is not
[code]#usm::alloc::host#, [code]#syclDevice# must either be contained by
[code]#syclContext# or it must be a descendent device of some device that
is contained by that context, otherwise this function throws a synchronous
[code]#exception# with the [code]#errc::invalid# error code.

Available only if `propertyListA` and `propertyListB` are specializations of the `properties` class.


a@
[source]
----
template <typename propertyListA, typename propertyListB>
sycl::ext::oneapi::experimental::annotated_ptr<void, propertyListB>
sycl::ext::oneapi::experimental::malloc(size_t numBytes,
                                        const queue& syclQueue,
                                        usm::alloc kind,
                                        const propertyListA &propList)
----
a@ Simplified form where [code]#syclQueue# provides the [code]#context#
and any necessary [code]#device#.
Zero or more runtime and compile-time constant properties can be provided to the allocation function
via an instance of `properties`.
The compile-time constant properties in `propList` will appear as properties of the returned `annotated_ptr`.
Runtime properties in `propList` will not appear as properties of the returned `annotated_ptr`.

Available only if `propertyListA` and `propertyListB` are specializations of the `properties` class.

a@
[source]
----
template <typename T, typename propertyListA, typename propertyListB>
sycl::ext::oneapi::experimental::annotated_ptr<T, propertyListB>
sycl::ext::oneapi::experimental::malloc(size_t count,
                                        const queue& syclQueue,
                                        usm::alloc kind,
                                        const propertyListA &propList)
----
a@ Simplified form where [code]#syclQueue# provides the [code]#context#
and any necessary [code]#device#.
Zero or more runtime and compile-time constant properties can be provided to the allocation function
via an instance of `properties`.
The compile-time constant properties in `propList` will appear as properties of the returned `annotated_ptr`.
Runtime properties in `propList` will not appear as properties of the returned `annotated_ptr`.

Available only if `propertyListA` and `propertyListB` are specializations of the `properties` class.

|====

=== USM Memory Allocation Properties

This section specifies the properties that can be passed to the USM memory allocation functions with `properties` support defined in Section <<section.usm.allocs>>.
A SYCL implementation or SYCL backend may support additional properties other than those defined here, provided they are defined in accordance with the
link:../experimental/sycl_ext_oneapi_properties.asciidoc[sycl_ext_oneapi_properties] extension.
If unsupported properties are passed to the USM memory allocation functions with `properties` support, the compiler will issue a diagnostic error.

All properties supported by `annotated_ptr` are supported by the USM memory allocation functions with `properties` support.
Unless otherwise specified, supported properties do not affect the behavior of the USM memory allocation functions with `properties` support.

[NOTE]
====
The USM memory allocation functions with `properties` support defined in this extension support all properties supported by `annotated_ptr`, as a convenience. This allows the user to attach all desired properties to the `annotated_ptr` in a single step.
These properties do not affect the behavior of the allocation functions, except where explicitly specified.
====

Table <<table.usm.malloc.properties>> lists properties that affect the behavior of the allocation functions.

[[table.usm.malloc.properties]]
.Properties that affect the behavior of the USM memory allocation functions with properties support
[options="header"]
|====
|Property|Description|Source
a|
alignment
| 	
If this property is present on an `annotated_ptr`, it indicates that the raw pointer has this alignment in bytes.
If this property is passed to a USM memory allocation function with `properties` support, it instructs the runtime to allocate memory with this alignment in bytes.
If the USM memory allocation function with `properties` support is templated on an allocation type `T` and the specified alignment is not suitable for an object of type `T` the compiler will issue a diagnostic error.
If the USM memory allocation function with `properties` support is not templated on an allocation type `T`, and the specified alignment is not suitable for objects with fundamental alignment whose size is less than or equal to the requested allocation size, the USM memory allocation function with `properties` support will throw a synchronous exception with the `errc:invalid` error code.
|
link:../proposed/sycl_ext_oneapi_annotated_ptr.asciidoc[sycl_ext_oneapi_annotated_ptr]
|====

This extension introduces an enumeration `sycl::ext::oneapi::experimental::usm_alloc_kind` with three values: `host`, `device`, and `shared`.
Table <<table.usm.malloc.devhostsh>> lists the new properties introduced by this extension.

[[table.usm.malloc.devhostsh]]
.New compile-time constant properties introduced by this extension
[options="header"]
|====
|Property|Values|Description|Supported By
a|
sycl::ext::oneapi::experimental::usm_alloc
| 	
sycl::ext::oneapi::experimental::usm_alloc_kind::host
sycl::ext::oneapi::experimental::usm_alloc_kind::device
sycl::ext::oneapi::experimental::usm_alloc_kind::shared
|
Indicates the kind of USM memory accessed by dereferencing this pointer and pointers derived from this pointer.
Instructs the runtime to allocate USM memory of this kind.
|
`annotated_ptr`
The USM memory allocation functions with `properties` support defined in this extension.
|====


The `sycl::ext::oneapi::experimental::usm_alloc` property is a compile-time constant property with a single non-type parameter. This parameter is a value belonging to the enumeration `sycl::ext::oneapi::experimental::usm_alloc_kind`.
The `sycl::ext::oneapi::experimental::usm_alloc` property is supported by `annotated_ptr` and the USM memory allocation functions defined in this extension.
If a USM memory allocation kind is also specified by `usm::alloc` the two kinds must be the same, otherwise the USM memory allocation function with `properties` support throws a synchronous exception with the `errc::invalid` error code.
If the USM memory allocation function with `properties` support does not have a parameter of type `usm::alloc`, and the USM memory allocation kind specified by the `usm_alloc` property passed to the function is different than the kind of memory allocated by the function, the compiler will issue a diagnostic error.

=== Deallocation

To avoid memory leaks, USM memory allocated using the USM memory allocation functions with `properties` support defined in this extension, must be deallocated using one of the `sycl::free` functions listed in Table 107 "USM Deallocation Functions" of Section 4.8.3.6 "Memory deallocation functions" of the core SYCL specification.

The following example shows how USM memory allocated using one of the functions defined in this extension should be deallocated, to avoid memory leaks.

==== Example

[source,c++]
----
using namespace sycl::ext::oneapi::experimental;

properties P1{alignment<512>};
// APtr is of type annotated_ptr<int*, decltype(P1)>
auto APtr = malloc_device<int>(N, q, P1);

// Deallocate the memory using the raw pointer of APtr
sycl::free(APtr.get(), q);
----

== Revision History

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|========================================
|Rev|Date|Author|Changes
|1|2022-07-07|Jessica Davies|*Initial public working draft*
|========================================
