:sectnums:

= `sycl_ext_intel_buffer_location_property`

:dpcpp: pass:[DPC++]

== Notice

Copyright (c) 2023 Intel Corporation.  All rights reserved.

NOTE: Khronos(R) is a registered trademark and SYCL(TM) and SPIR(TM) are
trademarks of The Khronos Group Inc.  OpenCL(TM) is a trademark of Apple Inc.
used by permission by Khronos.

== Contact

Jessica Davies, Intel (jessica 'dot' davies 'at' intel 'dot' com)

== Contributors

Jessica Davies, Intel

== Dependencies

This extension is written against the SYCL 2020 specification, revision 6.
All references below to the "core SYCL specification" or to section numbers in the
SYCL specification refer to that revision.

This extension also depends on the following other SYCL extensions:

- link:../experimental/sycl_ext_oneapi_properties.asciidoc[sycl_ext_oneapi_properties]
- link:../proposed/sycl_ext_oneapi_annotated_ptr.asciidoc[sycl_ext_oneapi_annotated_ptr]
- link:../proposed/sycl_ext_oneapi_usm_malloc_properties.asciidoc[sycl_ext_oneapi_usm_malloc_properties]

== Status

This is a proposed extension specification, intended to gather community
feedback.  Interfaces defined in this specification may not be implemented yet
or may be in a preliminary state.  The specification itself may also change in
incompatible ways before it is finalized.  *Shipping software products should
not rely on APIs defined in this specification.*

== Overview

This extension introduces a new compile-time constant property as defined in the link:../experimental/sycl_ext_oneapi_properties.asciidoc[sycl_ext_oneapi_properties] extension. The new property, `sycl::ext::intel::experimental::buffer_location`, takes a single integer parameter. On targets that provide more than one type of global memory, this property allows
users to choose the type of global memory allocated. 
This property is supported by `annotated_ptr` as defined in the link:../proposed/sycl_ext_oneapi_annotated_ptr.asciidoc[sycl_ext_oneapi_annotated_ptr] extension. It is also supported by the USM malloc functions with properties support defined in the link:../proposed/sycl_ext_oneapi_usm_malloc_properties.asciidoc[sycl_ext_oneapi_usm_malloc_properties] extension, if the memory allocated is of the USM device kind.


[NOTE]
====
In this document, we use the shortened form `annotated_ptr` to refer to the
proposed `sycl::ext::oneapi::experimental::annotated_ptr` class.
We also use the shortened form `properties` to refer to the `sycl::ext::oneapi::experimental::properties` class.
====

The purpose of this document is to clearly describe and specify the `sycl::ext::intel::experimental::buffer_location` property,
and related concepts, types, and mechanisms, and to give examples and context for their usage.

== Examples

[source,c++]
----
using namespace sycl::ext::oneapi::experimental;
using namespace sycl::ext::intel::experimental;

properties P1{buffer_location<1>};
properties P2{buffer_location<2>, usm_kind<sycl::usm::alloc::device>};
properties P3{buffer_location<3>, usm_kind<sycl::usm::alloc::shared>};

// APtr1 is of type annotated_ptr<int, decltype(properties{buffer_location<1>, usm_kind<sycl::usm::alloc::device>})>
auto APtr1 = malloc_device_annotated<int>(N, q, P1);

// APtr2 is of type annotated_ptr<int, decltype(properties{buffer_location<2>, usm_kind<sycl::usm::alloc::device>})>
auto APtr2 = malloc_annotated<int>(N, q, P2);

// APtr3 is of type annotated_ptr<int, decltype(properties{buffer_location<1>})>
auto APtr3 = malloc_annotated<int>(N, q, sycl::usm::alloc::device, P1);

// Error: USM kind is host USM, known at compile-time
auto APtr4 = malloc_host_annotated<int>(N, q, P1);

// Error: USM kind is shared USM, known at compile-time
auto APtr5 = malloc_annotated<int>(N, q, P3);

// Exception: USM kind is host USM, known only at runtime
auto APtr6 = malloc_annotated<int>(N, q, sycl::usm::alloc::host, P1);
----

== Specification

=== Feature test macro

This extension provides a feature-test macro as described in the core SYCL
specification, Section 6.3.3 "Feature test macros". Therefore, an
implementation supporting this extension must predefine the macro
`SYCL_EXT_INTEL_BUFFER_LOCATION` to one of the values defined in the table below.
Applications can test for the existence of this macro to determine if the
implementation supports this feature, or applications can test the macro's
value to determine which of the extension's features
the implementation supports.

[%header,cols="1,5"]
|===
|Value |Description
|1     |Initial extension version
|===


=== Compile-time Constant Buffer Location Property

The `sycl::ext::intel::experimental::buffer_location` property is a compile-time constant property with a single non-type parameter, as defined in link:../experimental/sycl_ext_oneapi_properties.asciidoc[sycl_ext_oneapi_properties].
Its parameter must be a positive integer value.
The `sycl::ext::intel::experimental::buffer_location` property is supported by `annotated_ptr`, and the USM memory allocation functions defined in link:../proposed/sycl_ext_oneapi_usm_malloc_properties.asciidoc[sycl_ext_oneapi_usm_malloc_properties], if the memory allocated is of the USM device kind.

[[table.buffer_location.property]]
.Compile-time constant buffer location property
[options="header"]
|====
|Property|Description
a|
sycl::ext::intel::experimental::buffer_location<location>
| 	
`location` is an integer greater than or equal to zero. If `location` is negative, an error will be reported.

If this property is on an `annotated_ptr` it indicates the memory pointed to by the raw pointer of the `annotated_ptr` is of type `location`. If the memory pointed to by the raw pointer of the `annotated_ptr` is not of this type, the behavior is undefined.

If this property is passed to a USM memory allocation function with `properties` support defined in link:../proposed/sycl_ext_oneapi_usm_malloc_properties.asciidoc[sycl_ext_oneapi_usm_malloc_properties], it instructs the runtime to allocate memory of this type.
If the USM kind is known at compile-time and is not device USM, the compiler will issue a diagnostic error.
If the USM kind is not known until runtime, and it is not device USM, then the allocation function will thrown an exception with the `errc::invalid` error code.

This property is ignored for non-FPGA devices, and for FPGA targets that do not provide more than one type of global memory.

|====


[source,c++]
----
namespace sycl::ext::intel::experimental {

struct buffer_location_key {
  template<int location>
  using value_t = sycl::ext::intel::experimental::properties::property_value<
    buffer_location_key, std::integral_constant<int, location>>;
};

template<int location>
inline constexpr buffer_location_key::value_t<location> buffer_location;

} // namespace sycl::ext::intel::experimental
----
